# ~/.config/starship.toml

[character]
success_symbol = " [➜ ](bold green)"
error_symbol = " [➜✗ ](bold red)"


# Custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """
